# Site settings
title: OpenGeoC贸rdoba
description: Descipci贸n proyecto
baseurl: "/opengeocordoba" # the subpath of your site, e.g. /blog
url: "http://www.sigdeletras.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Patricio Soriano
user_description: Ge贸grafo full-stack
email: pasoriano@sigdeletras.com
twitter_username: sigdeletras
github_username:  sigdeletras
gplus_username:  lorem_ipsum
disqus_username: pasoriano

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Temas
    url: /series
  - title: Etiquetas
    url: /tags
  - title: Sobre OpenGeoC贸rdoba
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
